# Generated by Django 4.1.7 on 2023-03-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=30)),
                ('t_gender', models.CharField(max_length=15)),
                ('t_age', models.IntegerField()),
                ('t_subject', models.CharField(max_length=30)),
                ('t_email', models.CharField(max_length=50)),
                ('t_phone', models.BigIntegerField()),
                ('t_pass', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'teacher_tb',
            },
        ),
    ]
